//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITeam")]
public interface ITeam
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeam/GetTeamNames", ReplyAction="http://tempuri.org/ITeam/GetTeamNamesResponse")]
    string[] GetTeamNames();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeam/GetTeamNames", ReplyAction="http://tempuri.org/ITeam/GetTeamNamesResponse")]
    System.Threading.Tasks.Task<string[]> GetTeamNamesAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITeamChannel : ITeam, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TeamClient : System.ServiceModel.ClientBase<ITeam>, ITeam
{
    
    public TeamClient()
    {
    }
    
    public TeamClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TeamClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TeamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TeamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[] GetTeamNames()
    {
        return base.Channel.GetTeamNames();
    }
    
    public System.Threading.Tasks.Task<string[]> GetTeamNamesAsync()
    {
        return base.Channel.GetTeamNamesAsync();
    }
}
