//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IThousandDays")]
public interface IThousandDays
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThousandDays/nextThousandDay", ReplyAction="http://tempuri.org/IThousandDays/nextThousandDayResponse")]
    System.DateTime nextThousandDay(System.DateTime celebrateDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThousandDays/nextThousandDay", ReplyAction="http://tempuri.org/IThousandDays/nextThousandDayResponse")]
    System.Threading.Tasks.Task<System.DateTime> nextThousandDayAsync(System.DateTime celebrateDate);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IThousandDaysChannel : IThousandDays, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ThousandDaysClient : System.ServiceModel.ClientBase<IThousandDays>, IThousandDays
{
    
    public ThousandDaysClient()
    {
    }
    
    public ThousandDaysClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ThousandDaysClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ThousandDaysClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ThousandDaysClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.DateTime nextThousandDay(System.DateTime celebrateDate)
    {
        return base.Channel.nextThousandDay(celebrateDate);
    }
    
    public System.Threading.Tasks.Task<System.DateTime> nextThousandDayAsync(System.DateTime celebrateDate)
    {
        return base.Channel.nextThousandDayAsync(celebrateDate);
    }
}
