//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="CountingBMIservice", ConfigurationName="ICounting")]
public interface ICounting
{
    
    [System.ServiceModel.OperationContractAttribute(Action="CountingBMIservice/ICounting/Bmi", ReplyAction="CountingBMIservice/ICounting/BmiResponse")]
    double Bmi(double weight, double height);
    
    [System.ServiceModel.OperationContractAttribute(Action="CountingBMIservice/ICounting/Bmi", ReplyAction="CountingBMIservice/ICounting/BmiResponse")]
    System.Threading.Tasks.Task<double> BmiAsync(double weight, double height);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICountingChannel : ICounting, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CountingClient : System.ServiceModel.ClientBase<ICounting>, ICounting
{
    
    public CountingClient()
    {
    }
    
    public CountingClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CountingClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CountingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CountingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double Bmi(double weight, double height)
    {
        return base.Channel.Bmi(weight, height);
    }
    
    public System.Threading.Tasks.Task<double> BmiAsync(double weight, double height)
    {
        return base.Channel.BmiAsync(weight, height);
    }
}
